version: "3"

services:
  weather-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    restart: on-failure
    volumes:
    - "./test-tmp/backend/config:/config"

  mysqldb:
    image: mysql:8.0.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: "db1"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"