version: "3"

services:
  weather-app:
    environment:
      spring_profiles_active: local
    volumes:
    - "./test-tmp/backend/config:/config"

  weather-mock:
    image: rodolpheche/wiremock
    ports:
      - 3000:8080