name: CI pipeline

on: [push]

jobs:
  build:
    name: Feature tests
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   name: Start the test environment
          run: ./start.sh --build --detach

      -   name: Ensure services up and ready
          run: ./ensure_services_ready.sh

      -   name: Run feature tests
          run: ./test-features.sh